# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by Shampoohat library 0.0.8 on 2019-05-14 16:44:46.

require 'shampoohat/savon_service'
require 'yahoo_ad_api/V201901/page_feed_item_service_registry'

module YahooAdApi; module V201901; module PageFeedItemService
  class PageFeedItemService < Shampoohat::SavonService
    def initialize(config, endpoint)
      namespace = 'http://ss.yahooapis.jp/V201901/PageFeedItem'
      default_ns = 'ns1'
      super(config, endpoint, namespace, :V201901, default_ns)
    end

    def add_download_job(*args, &block)
      return execute_action('add_download_job', args, &block)
    end

    def add_download_job_to_xml(*args)
      return get_soap_xml('add_download_job', args)
    end

    def get_job_status(*args, &block)
      return execute_action('get_job_status', args, &block)
    end

    def get_job_status_to_xml(*args)
      return get_soap_xml('get_job_status', args)
    end

    def get_upload_url(*args, &block)
      return execute_action('get_upload_url', args, &block)
    end

    def get_upload_url_to_xml(*args)
      return get_soap_xml('get_upload_url', args)
    end

    def get_review_summary(*args, &block)
      return execute_action('get_review_summary', args, &block)
    end

    def get_review_summary_to_xml(*args)
      return get_soap_xml('get_review_summary', args)
    end

    def get(*args, &block)
      return execute_action('get', args, &block)
    end

    def get_to_xml(*args)
      return get_soap_xml('get', args)
    end

    private

    def get_service_registry()
      return PageFeedItemServiceRegistry
    end

    def get_module()
      return YahooAdApi::V201901::PageFeedItemService
    end
  end
end; end; end
