# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by Shampoohat library 0.0.2 on 2016-08-17 14:30:27.

require 'shampoohat/savon_service'
require 'yahoo_ad_api/V6_0/ad_group_criterion_service_registry'

module YahooAdApi; module V6_0; module AdGroupCriterionService
  class AdGroupCriterionService < Shampoohat::SavonService
    def initialize(config, endpoint)
      namespace = 'http://ss.yahooapis.jp/V6'
      default_ns = 'ns1'
      super(config, endpoint, namespace, :V6_0, default_ns)
    end

    def get(*args, &block)
      return execute_action('get', args, &block)
    end

    def mutate(*args, &block)
      return execute_action('mutate', args, &block)
    end

    private

    def get_service_registry()
      return AdGroupCriterionServiceRegistry
    end

    def get_module()
      return YahooAdApi::V6_0::AdGroupCriterionService
    end
  end
end; end; end
