# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2015, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by Shampoohat library 0.0.6 on 2017-08-04 20:58:12.

require 'shampoohat/savon_service'
require 'yahoo_ad_api/V6_3/campaign_export_service_registry'

module YahooAdApi; module V6_3; module CampaignExportService
  class CampaignExportService < Shampoohat::SavonService
    def initialize(config, endpoint)
      namespace = 'http://ss.yahooapis.jp/V6'
      default_ns = 'ns1'
      super(config, endpoint, namespace, :V6_3, default_ns)
    end

    def get(*args, &block)
      return execute_action('get', args, &block)
    end

    def get_to_xml(*args)
      return get_soap_xml('get', args)
    end

    def add_job(*args, &block)
      return execute_action('add_job', args, &block)
    end

    def add_job_to_xml(*args)
      return get_soap_xml('add_job', args)
    end

    private

    def get_service_registry()
      return CampaignExportServiceRegistry
    end

    def get_module()
      return YahooAdApi::V6_3::CampaignExportService
    end
  end
end; end; end
